import { View, Text, ScrollView } from "react-native";

export default function Tarefas() {
  return (
    <ScrollView>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <View>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
    </View>
    <View>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
    </View>
    <View>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
    </View>
    <View>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
      <Text>Tarefas</Text>
    </View>
    </ScrollView>
  );
}
