import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  scrollView: { flex: 1, backgroundColor: "#fff" },
  content: { alignItems: "center", paddingBottom: 120 },
  topContainer: {
    backgroundColor: "#3b82f6",
    paddingTop: 48,
    paddingBottom: 24,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    width: width,
  },
  searchRow: { flexDirection: "row", alignItems: "center" },
  input: {
    backgroundColor: "#fff",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginLeft: 12,
    flex: 1,
    fontSize: 14,
  },
  saudacao: { color: "white", textAlign: "right", marginTop: 8, fontSize: 16 },
  nome: { fontWeight: "bold" },
  section: { width: width, paddingHorizontal: 16, paddingTop: 24 },
  titulo: { fontSize: 20, fontWeight: "bold", marginBottom: 8 },
  conexoes: { flexDirection: "row", gap: 12, marginBottom: 24 },
  conexaoItem: { position: "relative" },
  foto: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "#3b82f6",
  },
  status: {
    position: "absolute",
    top: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "white",
  },
  card: {
    backgroundColor: "#3b82f6",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 8,
  },
  cardTexto: { color: "white", fontSize: 14 },
  cardCinza: {
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    padding: 16,
    marginTop: 24,
  },
  cardCinzaTitulo: { fontWeight: "bold", marginBottom: 4 },
  cardLink: { color: "#3b82f6", fontWeight: "bold" },
  fotoPost: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#3b82f6",
    marginRight: 10,
  },
  iconeRowFixed: {
    position: "absolute",
    bottom: 20,
    width: width,
    flexDirection: "row",
    justifyContent: "center",
    gap: 24,
  },
  iconeBotao: { backgroundColor: "#3b82f6", padding: 16, borderRadius: 999 },
});
export default styles;